all:
	/home/ky/work/gcc-linaro-arm-linux-gnueabihf-4.7-2013.03-20130313_linux/bin/arm-linux-gnueabihf-gcc httpauth.c capture_thread1.c -o app
	@rm -f *.o *.mod.o *.mod.c *.symvers *.markers *~ *.order
	
clean:
	@rm -f *.ko *.o *.mod.o *.mod.c *.symvers *.markers *~ *_app *.order
