######################################################################
# Automatically generated by qmake (2.01a) ?? 8? 18 14:57:41 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . can image keyPad led_gpiokey sql
INCLUDEPATH += . keyPad can sql led_gpiokey

# Input
HEADERS += audio_dlg.h \
           buzzer.h \
           config_all.h \
           mainwindow.h \
           serial_app.h \
           serial_dlg.h \
           set_dlg.h \
           ui_time_dlg.h \
           can/socketcan.h \
           can/threadcanreadmonitor.h \
           keyPad/inputwidget.h \
           keyPad/ipmethod.h \
           led_gpiokey/qtkeyledctrl.h \
           sql/change.h \
           sql/deletestu.h \
           sql/findstu.h \
           sql/insert.h \
           sql/querystu.h \
           sql/student.h
FORMS += audio_dlg.ui \
         buzzer.ui \
         mainwindow.ui \
         serial_dlg.ui \
         set_dlg.ui \
         keyPad/inputwidget.ui \
         sql/change.ui \
         sql/deletestu.ui \
         sql/find.ui \
         sql/insert.ui \
         sql/querystu.ui \
         sql/student.ui
SOURCES += audio_dlg.cpp \
           buzzer.cpp \
           main.cpp \
           mainwindow.cpp \
           serial_app.cpp \
           serial_dlg.cpp \
           set_dlg.cpp \
           can/socketcan.cpp \
           can/threadcanreadmonitor.cpp \
           keyPad/inputwidget.cpp \
           keyPad/ipmethod.cpp \
           led_gpiokey/qtkeyledctrl.cpp \
           sql/change.cpp \
           sql/deletestu.cpp \
           sql/findstu.cpp \
           sql/insert.cpp \
           sql/querystu.cpp \
           sql/student.cpp
RESOURCES += image/serial.qrc
TRANSLATIONS += zh.ts
